version: '3.8'
services:
  app:
    build: .
    container_name: app
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_URL=mongodb://admin:admin11@mongo/trivia?authSource=admin
      - WS_URL=connect:ws://localhost:8080
  mongo:
    image: 'mongo:7.0.5'
    environment:
      - MONGO_INITDB_DATABASE=trivia
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin11
