version: '3.8'
services:
  mongo:
    image: 'mongo:7.0.5'
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=trivia
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin11
